version: '3'

services:
  postgres:
    image: 'postgres:13-alpine'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: 'dpage/pgadmin4:5.6'
    depends_on:
      - postgres
    ports:
      - 15432:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  postgres:
  pgadmin:

# version: '3'
# services: 
#   prisma:
#     image: prismagraphql/prisma:1.8
#     restart: always
#     ports:
#     - 4466:4466
#     enviroment:
#       PRISMA_CONFIG:
#         port: 4466
#         # uncomment the next line and provide the env vas PRISMA_MANAGEMENT_API_SECRET=mysecret to activate
#         # managementApiSecret: my-secret
#         databases:
#           default:
#             connector: postgres
#             database: prisma
#             host: host.docker.internal
#             port: 5432
#             user : postgres
#             password: postgres
#             migrations: true
